sources:
  - path: /dogu
    type: dogus
    tag: warp
  - path: externals
    type: externals
target: /var/www/html/warp/menu.json
order:
  Development Apps: 100
support:
  - identifier: docsCloudoguComUrl
    external: true
    href: https://docs.cloudogu.com/
  - identifier: aboutCloudoguToken
    external: false
    href: /info/about
  - identifier: platform
    external: true
    href: https://platform.cloudogu.com
